data:
  augmentation:
    homographic:
      enable: false
      params:
        allow_artifacts: true
        max_angle: 0.3
        patch_ratio: 0.9
        perspective: true
        perspective_amplitude_x: 0.3
        perspective_amplitude_y: 0.3
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
      valid_border_margin: 9
    photometric:
      enable: true
      params:
        additive_gaussian_noise:
          stddev_range:
          - 0
          - 10
        additive_shade:
          kernel_size_range:
          - 100
          - 150
          prob: 0.5
          transparency_range:
          - -0.5
          - 0.5
        additive_speckle_noise:
          prob_range:
          - 0
          - 0.0035
        motion_blur:
          kernel_size:
          - 13
          - 21
          prob: 0.1
        random_brightness:
          delta_range:
          - -30.0
          - 40.0
        random_contrast:
          strength_range:
          - 0.3
          - 1.2
      primitives:
      - random_brightness
      - random_contrast
      - additive_gaussian_noise
      - additive_shade
      - motion_blur
  image_dirs:
  - google_landmarks/images
  - OpenLORIS-Scene/images
  load_targets: true
  name: distillation
  preprocessing:
    grayscale: true
    resize:
    - 480
    - 640
  targets:
  - dir: global_descriptors
    keys:
    - global_descriptor
  - dir: superpoint_predictions
    keys:
    - local_descriptor_map
    - dense_scores
  truncate:
  - 185000
  - null
  - null
  validation_size: 192
keep_checkpoints: 100
model:
  batch_size: 16
  depth_multiplier: 0.75
  dropout_keep_prob: null
  eval_batch_size: 16
  global:
    dimensionality_reduction: 4096
    intermediate_proj: 0
    n_clusters: 32
  image_channels: 1
  learning_rate:
  - 0.001
  - 0.0001
  - 1.0e-05
  learning_rate_step:
  - 60000
  - 80000
  local:
    descriptor_dim: 256
  loss_weights: uncertainties
  name: hf_net
  train_backbone: true
save_interval: 5000
train_iter: 85000
validation_interval: 500
weights: mobilenet_v2_0.75_224/mobilenet_v2_0.75_224.ckpt
